import "server-only";
import { randomBytes } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { POSTER_MAX_BYTES, POSTER_URL_PREFIX } from "@@/data/projects";

export const POSTER_DIR = path.join(
  /*turbopackIgnore: true*/ process.cwd(),
  "public",
  "images",
  "our-projects",
);

/** Uploaded file names are always generated by savePoster, so anything else is rejected. */
export const POSTER_FILE_PATTERN = /^[a-z0-9-]+\.(jpg|png|webp|avif)$/;

export const POSTER_CONTENT_TYPES = {
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
  avif: "image/avif",
} as const;

type PosterExt = keyof typeof POSTER_CONTENT_TYPES;

/** Detects the real image type from its first bytes; the browser-reported type can't be trusted. */
function sniffImage(bytes: Buffer): PosterExt | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "jpg";
  }
  if (
    bytes.length >= 8 &&
    bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
  ) {
    return "png";
  }
  if (
    bytes.length >= 12 &&
    bytes.toString("ascii", 0, 4) === "RIFF" &&
    bytes.toString("ascii", 8, 12) === "WEBP"
  ) {
    return "webp";
  }
  if (bytes.length >= 12 && bytes.toString("ascii", 4, 8) === "ftyp") {
    const brand = bytes.toString("ascii", 8, 12);
    if (brand === "avif" || brand === "avis") return "avif";
  }
  return null;
}

function slugify(title: string) {
  return (
    title
      .toLowerCase()
      .normalize("NFKD")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 50) || "poster"
  );
}

export type PosterResult = { ok: true; path: string } | { ok: false; error: string };

export async function savePoster(file: File, title: string): Promise<PosterResult> {
  if (file.size > POSTER_MAX_BYTES) {
    return {
      ok: false,
      error: `Poster is ${Math.ceil(file.size / 1024)} KB. The maximum is ${POSTER_MAX_BYTES / 1024} KB.`,
    };
  }
  const bytes = Buffer.from(await file.arrayBuffer());
  const ext = sniffImage(bytes);
  if (!ext) {
    return { ok: false, error: "Poster must be a JPG, PNG, WebP or AVIF image." };
  }
  const name = `${slugify(title)}-${randomBytes(4).toString("hex")}.${ext}`;
  await mkdir(POSTER_DIR, { recursive: true });
  await writeFile(path.join(POSTER_DIR, name), bytes);
  return { ok: true, path: `${POSTER_URL_PREFIX}${name}` };
}

/** Removes an uploaded poster; paths outside /images/our-projects/ are left alone. */
export async function deletePoster(posterPath: string | undefined) {
  if (!posterPath?.startsWith(POSTER_URL_PREFIX)) return;
  const name = posterPath.slice(POSTER_URL_PREFIX.length);
  if (!POSTER_FILE_PATTERN.test(name)) return;
  try {
    await unlink(path.join(POSTER_DIR, name));
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}

export async function readPoster(name: string) {
  if (!POSTER_FILE_PATTERN.test(name)) return null;
  try {
    const bytes = await readFile(path.join(POSTER_DIR, name));
    const ext = name.slice(name.lastIndexOf(".") + 1) as PosterExt;
    return { bytes, contentType: POSTER_CONTENT_TYPES[ext] };
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
}
